{{ config(materialized='ephemeral') }}

WITH src_data AS (
    SELECT SECURITY_CODE AS SECURITY_CODE,
    SECURITY_NAME AS SECURITY_NAME,
    SECTOR AS SECTOR_NAME,
    INDUSTRY AS INDUSTRY_NAME,
    COUNTRY AS COUNTRY_CODE,
    EXCHANGE AS EXCHANGE_CODE,
    LOAD_TS AS LOAD_TS,
    'SEED.ACB_BANK_SECURITY_INFO' AS RECORD_SOURCE
    FROM {{ source('seeds', 'ACB_BANK_SECURITY_INFO') }}
),
hashed AS (
    SELECT {{ dbt_utils.generate_surrogate_key(['SECURITY_CODE'])}} AS SECURITY_HKEY,
    {{ dbt_utils.generate_surrogate_key(['SECURITY_CODE', 'SECURITY_NAME', 'SECTOR_NAME',
    'INDUSTRY_NAME', 'COUNTRY_CODE', 'EXCHANGE_CODE'])}} AS SECURITY_HDIFF,
    * EXCLUDE LOAD_TS,
    LOAD_TS AS LOAD_TS_UTC
    FROM src_data
)

SELECT * FROM hashed